/** Type-only bridge to the kernel contracts. Nothing here reaches the bundle. */
export type {
  AgentDefinition,
  AgentInstance,
  AgentOutput,
  AgentPerformance,
  AgentState,
  ApprovalRequest,
  AuditEntry,
  ConceptInfo,
  EdgeKind,
  EventType,
  FileKind,
  Finding,
  GraphEdge,
  GraphNode,
  Governor,
  IntentClassification,
  JournalEntry,
  KernelEvent,
  KernelStatus,
  McpServerConfig,
  McpServerStatus,
  MemoryCategory,
  MemoryRecord,
  NodeType,
  PlanStep,
  RadialAction,
  RadialKind,
  RadialResult,
  Reversibility,
  SearchHit,
  ToolAction,
  ToolDefinition,
  ToolPolicy,
  ToolResult,
  TriggerRule,
  WorkflowDefinition,
  Workspace,
  WorkspaceStatus,
} from "../../src/kernel/types";
export type { GraphSlice, NodeDetail, RadialMenu, WorkspaceDetail } from "../../src/server/api-contract";

import type { Governor } from "../../src/kernel/types";
export type GovernorSnapshot = ReturnType<Governor["snapshot"]>;
