import type { AgentDefinition } from "../kernel/types";

/**
 * The agent catalog (DESIGN.md 6). Every agent follows schemas/agent.schema.json.
 * `offlineSkill` names the rule-based skill in src/agents/skills used when Claude is not configured.
 */

const READ = ["fs.list_files", "fs.read_file", "fs.search_text", "search.semantic", "memory.recall"];
const GIT_READ = ["git.status", "git.log", "git.diff"];
/** Writes into the workspace output folder: a scratch area, reversible. */
const WRITE = ["fs.write_output"];
/** Writes to project files: compensable (journaled, undoable), approval in "ask" mode. */
const PROJECT_WRITE = ["fs.write_file"];

function agent(def: AgentDefinition): AgentDefinition {
  return def;
}

export const AGENT_CATALOG: AgentDefinition[] = [
  // --- System agents (always available) ---
  agent({
    id: "commander",
    name: "Commander Agent",
    role: "Merges the outputs of a swarm into one result and resolves conflicts between agents",
    group: "system",
    goals: ["Produce one coherent result per workspace", "Resolve disagreements between agents explicitly"],
    tools: [...READ, ...WRITE],
    memory: ["project_history", "architecture_decision"],
    constraints: ["Never drop a high or critical finding when merging", "Name the agents behind every conflict"],
    offlineSkill: "commander",
  }),
  agent({
    id: "memory_agent",
    name: "Memory Agent",
    role: "Keeps project memory, decisions, standards and preferences up to date",
    group: "system",
    goals: ["Record what each workspace learned", "Recall relevant memory for new intents"],
    tools: ["memory.recall", "memory.remember", ...READ],
    memory: ["preference", "project_history", "architecture_decision", "coding_standard", "translation_guide", "file_relationship", "agent_performance"],
    constraints: ["Store facts, not guesses", "Never store secrets"],
    offlineSkill: "memory",
  }),
  agent({
    id: "security_agent",
    name: "Security Agent",
    role: "Guards tool permissions and scans workspaces for secrets and unsafe code",
    group: "system",
    goals: ["Keep write and execute actions under the tool policy", "Flag leaked credentials and unsafe patterns"],
    tools: [...READ, ...GIT_READ],
    memory: ["coding_standard"],
    constraints: ["Report the file and line of a secret, never its value"],
    offlineSkill: "security",
  }),
  agent({
    id: "scheduler_agent",
    name: "Scheduler Agent",
    role: "Orders tasks by priority and dependencies and keeps agent concurrency within limits",
    group: "system",
    goals: ["Run independent steps in parallel", "Never start a step before its dependencies finish"],
    tools: ["memory.recall"],
    memory: ["agent_performance"],
    constraints: ["Respect the maximum concurrent agents setting"],
    offlineSkill: "scheduler",
  }),
  agent({
    id: "ux_agent",
    name: "UX Agent",
    role: "Reviews user-facing screens for usability and accessibility",
    group: "system",
    goals: ["Find accessibility and usability problems in UI files"],
    tools: [...READ],
    memory: ["preference"],
    constraints: ["Cite the file and element for every finding"],
    offlineSkill: "ux",
  }),

  // --- Engineering agents ---
  agent({
    id: "systems_architect",
    name: "Systems Architect",
    role: "Maps module boundaries and dependencies and checks them against architecture decisions",
    group: "engineering",
    goals: ["Map dependencies between modules", "Find cycles and boundary violations"],
    tools: [...READ, ...GIT_READ],
    memory: ["architecture_decision", "file_relationship"],
    constraints: ["Base every claim on an import or file you read"],
    offlineSkill: "architecture",
  }),
  agent({
    id: "gameplay_architect",
    name: "Gameplay Architect",
    role: "Designs and reviews gameplay systems such as combat, inventory and economy",
    group: "engineering",
    goals: ["Keep gameplay systems decoupled and data driven", "Spot balance risks in formulas"],
    tools: [...READ],
    memory: ["architecture_decision", "file_relationship"],
    constraints: ["Separate design opinions from defects"],
    offlineSkill: "architecture",
  }),
  agent({
    id: "fullstack_engineer",
    name: "Fullstack Engineer",
    role: "Implements features across the stack following the coding standards",
    group: "engineering",
    goals: ["Implement the requested change with tests", "Follow the project's coding standards"],
    tools: [...READ, ...GIT_READ, ...WRITE, ...PROJECT_WRITE, "proc.run_tests"],
    memory: ["coding_standard", "architecture_decision"],
    constraints: ["Write only inside the project root", "Keep changes minimal and reviewable", "Project writes are journaled and can be undone by the user"],
    offlineSkill: "implementation",
  }),
  agent({
    id: "qa_engineer",
    name: "QA Engineer",
    role: "Checks test coverage and runs the test suite",
    group: "engineering",
    goals: ["Find untested code paths", "Run the tests and report failures"],
    tools: [...READ, "proc.run_tests"],
    memory: ["coding_standard"],
    constraints: ["Never mark a failing test as passing"],
    offlineSkill: "qa",
  }),
  agent({
    id: "code_reviewer",
    name: "Code Reviewer",
    role: "Reviews code for defects, risky patterns and standard violations",
    group: "engineering",
    goals: ["Find defects before they ship", "Check code against the coding standards"],
    tools: [...READ, ...GIT_READ],
    memory: ["coding_standard"],
    constraints: ["Every finding names a file and line", "Rank findings by severity"],
    offlineSkill: "code_review",
  }),
  agent({
    id: "devops_engineer",
    name: "DevOps Engineer",
    role: "Owns build, CI and deployment configuration",
    group: "engineering",
    goals: ["Keep builds reproducible", "Make deployment one command"],
    tools: [...READ, ...GIT_READ, "proc.deploy", "proc.run_tests"],
    memory: ["architecture_decision"],
    constraints: ["Deploy only through the configured deploy command"],
    offlineSkill: "devops",
  }),
  agent({
    id: "planner",
    name: "Planner",
    role: "Splits a goal into ordered, testable tasks",
    group: "engineering",
    goals: ["Produce a task list with dependencies and acceptance checks"],
    tools: [...READ],
    memory: ["project_history", "architecture_decision"],
    constraints: ["Every task has a clear done condition"],
    offlineSkill: "planning",
  }),
  agent({
    id: "documentation",
    name: "Documentation",
    role: "Writes and updates documentation for code and features",
    group: "engineering",
    goals: ["Keep docs in step with the code", "Document every exported symbol that changed"],
    tools: [...READ, ...WRITE],
    memory: ["coding_standard"],
    constraints: ["Write docs under the workspace output folder unless told otherwise"],
    offlineSkill: "docs",
  }),

  // --- Creative agents ---
  agent({
    id: "writer",
    name: "Writer",
    role: "Drafts and edits prose: copy, articles, release notes",
    group: "creative",
    goals: ["Write clear copy in the project's voice"],
    tools: [...READ, ...WRITE],
    memory: ["preference", "translation_guide"],
    constraints: ["Mark facts that need checking"],
    offlineSkill: "docs",
  }),
  agent({
    id: "designer",
    name: "Designer",
    role: "Reviews and proposes visual and interaction design",
    group: "creative",
    goals: ["Keep the interface consistent and legible"],
    tools: [...READ],
    memory: ["preference"],
    constraints: ["Tie every suggestion to a screen or file"],
    offlineSkill: "ux",
  }),
  agent({
    id: "researcher",
    name: "Researcher",
    role: "Finds and summarizes what the project already knows about a topic",
    group: "creative",
    goals: ["Collect the relevant files and facts for a question"],
    tools: [...READ],
    memory: ["project_history", "architecture_decision"],
    constraints: ["Cite the file for every fact"],
    offlineSkill: "research",
  }),
  agent({
    id: "localization_expert",
    name: "Localization Expert",
    role: "Adapts content to a target locale, beyond word-for-word translation",
    group: "creative",
    goals: ["Adapt dates, numbers, idioms and tone to the locale"],
    tools: [...READ, ...WRITE],
    memory: ["translation_guide"],
    constraints: ["Follow the glossary and style guide"],
    offlineSkill: "localization",
  }),
  agent({
    id: "narrative_designer",
    name: "Narrative Designer",
    role: "Shapes story, dialogue and world text",
    group: "creative",
    goals: ["Keep lore and dialogue consistent"],
    tools: [...READ],
    memory: ["project_history"],
    constraints: ["Flag contradictions with existing lore"],
    offlineSkill: "research",
  }),
  agent({
    id: "translator",
    name: "Translator",
    role: "Translates text into the target language using the glossary",
    group: "creative",
    goals: ["Translate accurately and consistently with the glossary"],
    tools: [...READ, ...WRITE],
    memory: ["translation_guide"],
    constraints: ["Never translate defined terms inconsistently", "Keep formatting and placeholders intact"],
    offlineSkill: "localization",
  }),
  agent({
    id: "brand_analyst",
    name: "Brand Analyst",
    role: "Extracts voice, tone and key terms from existing content",
    group: "creative",
    goals: ["Describe the brand voice and list terms that must not change"],
    tools: [...READ],
    memory: ["translation_guide", "preference"],
    constraints: ["Quote the source text for every voice trait"],
    offlineSkill: "brand",
  }),
  agent({
    id: "localization_qa",
    name: "Localization QA",
    role: "Checks translated content for terminology, length and tone problems",
    group: "creative",
    goals: ["Catch glossary violations, truncation risks and untranslated strings"],
    tools: [...READ],
    memory: ["translation_guide"],
    constraints: ["Report the string and file for every issue"],
    offlineSkill: "localization",
  }),
  agent({
    id: "seo_reviewer",
    name: "SEO Reviewer",
    role: "Reviews titles, metadata and language tags for search",
    group: "creative",
    goals: ["Every page has a localized title, description and lang attribute"],
    tools: [...READ],
    memory: ["translation_guide"],
    constraints: ["Check the rendered HTML, not assumptions"],
    offlineSkill: "seo",
  }),
  agent({
    id: "qa_reviewer",
    name: "QA Reviewer",
    role: "Final quality check of a deliverable against its source",
    group: "creative",
    goals: ["Check terms, numbering and cross-references against the source"],
    tools: [...READ],
    memory: ["translation_guide"],
    constraints: ["Compare against the source, line by line where possible"],
    offlineSkill: "legal",
  }),

  // --- Business agents ---
  agent({
    id: "finance",
    name: "Finance",
    role: "Checks figures, prices and budgets in documents",
    group: "business",
    goals: ["Find every monetary figure and check totals"],
    tools: [...READ],
    memory: ["project_history"],
    constraints: ["Never round figures silently"],
    offlineSkill: "finance",
  }),
  agent({
    id: "legal",
    name: "Legal Agent",
    role: "Reads contracts: defined terms, obligations, dates and risky clauses",
    group: "business",
    goals: ["List defined terms and key clauses", "Flag one-sided or missing clauses"],
    tools: [...READ],
    memory: ["translation_guide"],
    constraints: ["This is not legal advice; say so in the output"],
    offlineSkill: "legal",
  }),
  agent({
    id: "marketing",
    name: "Marketing",
    role: "Reviews positioning, messaging and calls to action",
    group: "business",
    goals: ["Make the value clear in the first screen"],
    tools: [...READ],
    memory: ["preference"],
    constraints: ["No claims without a source"],
    offlineSkill: "brand",
  }),
  agent({
    id: "operations",
    name: "Operations",
    role: "Turns goals into checklists, owners and schedules",
    group: "business",
    goals: ["Produce an actionable checklist"],
    tools: [...READ],
    memory: ["project_history"],
    constraints: ["Every item has an owner role and a done condition"],
    offlineSkill: "planning",
  }),
];

/** Role words used in intents and the spec, mapped to catalog ids. */
export const AGENT_ALIASES: Record<string, string> = {
  architect: "systems_architect",
  "lead architect": "systems_architect",
  reviewer: "code_reviewer",
  "code reviewer": "code_reviewer",
  qa: "qa_engineer",
  tester: "qa_engineer",
  engineer: "fullstack_engineer",
  developer: "fullstack_engineer",
  docs: "documentation",
  documentation: "documentation",
  "translation agent": "translator",
  translation: "translator",
  "legal agent": "legal",
  lawyer: "legal",
  seo: "seo_reviewer",
  brand: "brand_analyst",
  commander: "commander",
  memory: "memory_agent",
  security: "security_agent",
  scheduler: "scheduler_agent",
  ux: "ux_agent",
};

export const SYSTEM_AGENT_IDS = AGENT_CATALOG.filter((a) => a.group === "system").map((a) => a.id);

export function findAgent(idOrAlias: string): AgentDefinition | undefined {
  const key = idOrAlias.trim().toLowerCase();
  const id = AGENT_ALIASES[key] ?? key.replace(/[\s-]+/g, "_");
  return AGENT_CATALOG.find((a) => a.id === id);
}
