// Generates the small assets the examples use, so the repository needs no
// third-party files:
//   examples/assets/vase.obj     a lathe-turned vase (triangles, normals, UVs)
//   examples/assets/tiles.png    a 512x512 ceramic tile texture
//   examples/assets/studio.hdr   a 256x128 studio environment with softboxes
//
//   node tools/make-assets.mjs

import { mkdirSync, writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { encodeHDR } from '../src/sky/hdr.js';
import { dirFromEquirect } from '../src/sky/atmosphere.js';
import { fbm3 } from '../src/core/noise.js';

const OUT = fileURLToPath(new URL('../examples/assets/', import.meta.url));
mkdirSync(OUT, { recursive: true });

// ---------------------------------------------------------------- vase.obj
function vase() {
  // Profile: radius as a function of height (metres), from base to lip.
  const profile = [];
  const H = 0.4, steps = 32;
  for (let i = 0; i <= steps; i++) {
    const y = (i / steps) * H;
    const u = y / H;
    const r = 0.07 + 0.08 * Math.sin(Math.PI * Math.pow(u, 0.8)) - 0.035 * u + 0.02 * Math.pow(u, 6);
    profile.push([r, y]);
  }
  const wall = 0.006;
  const inner = profile.slice(4).map(([r, y]) => [r - wall, y]).reverse();
  const pts = [[0, 0], ...profile, ...inner, [0, profile[4][1]]];
  const seg = 48;
  const lines = ['# lathe-turned vase, generated by tools/make-assets.mjs'];
  const v = [], vt = [], vn = [];
  for (let s = 0; s <= seg; s++) {
    const a = (s / seg) * Math.PI * 2;
    for (let k = 0; k < pts.length; k++) {
      const [r, y] = pts[k];
      v.push([r * Math.cos(a), y, r * Math.sin(a)]);
      vt.push([s / seg, k / (pts.length - 1)]);
      // Profile tangent -> normal in the r-y plane.
      const [r0, y0] = pts[Math.max(0, k - 1)], [r1, y1] = pts[Math.min(pts.length - 1, k + 1)];
      let nr = y1 - y0, ny = -(r1 - r0);
      const l = Math.hypot(nr, ny) || 1;
      nr /= l; ny /= l;
      vn.push([nr * Math.cos(a), ny, nr * Math.sin(a)]);
    }
  }
  for (const p of v) lines.push(`v ${p.map((x) => x.toFixed(4)).join(' ')}`);
  for (const p of vt) lines.push(`vt ${p.map((x) => x.toFixed(3)).join(' ')}`);
  for (const p of vn) lines.push(`vn ${p.map((x) => x.toFixed(3)).join(' ')}`);
  const row = pts.length;
  for (let s = 0; s < seg; s++) {
    for (let k = 0; k < row - 1; k++) {
      const a = s * row + k + 1, b = (s + 1) * row + k + 1;
      const f = (i) => `${i}/${i}/${i}`;
      lines.push(`f ${f(a)} ${f(a + 1)} ${f(b + 1)} ${f(b)}`);
    }
  }
  return lines.join('\n') + '\n';
}
writeFileSync(OUT + 'vase.obj', vase());

// ---------------------------------------------------------------- tiles.png
function png(width, height, rgba) {
  const crcTable = new Uint32Array(256).map((_, n) => {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc = (buf) => {
    let c = 0xffffffff;
    for (const b of buf) c = crcTable[(c ^ b) & 255] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, data) => {
    const out = Buffer.alloc(12 + data.length);
    out.writeUInt32BE(data.length, 0);
    out.write(type, 4, 'ascii');
    data.copy(out, 8);
    out.writeUInt32BE(crc(out.subarray(4, 8 + data.length)), 8 + data.length);
    return out;
  };
  const raw = Buffer.alloc((width * 4 + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (width * 4 + 1)] = 0;
    Buffer.from(rgba.buffer, rgba.byteOffset + y * width * 4, width * 4).copy(raw, y * (width * 4 + 1) + 1);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr.set([8, 6, 0, 0, 0], 8);
  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    chunk('IHDR', ihdr), chunk('IDAT', deflateSync(raw)), chunk('IEND', Buffer.alloc(0)),
  ]);
}

function tiles(size = 512) {
  const px = new Uint8Array(size * size * 4);
  const n = 4, grout = 0.035;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const u = (x / size) * n, v = (y / size) * n;
      const tx = Math.floor(u), ty = Math.floor(v);
      const fx = u - tx, fy = v - ty;
      const edge = Math.min(fx, 1 - fx, fy, 1 - fy);
      const o = (y * size + x) * 4;
      if (edge < grout) {
        const g = 150 + 20 * fbm3(u * 8, v * 8, 1, 3);
        px.set([g * 1.2, g * 1.17, g * 1.1, 255].map((c) => Math.min(255, c)), o);
      } else {
        // Each tile a slightly different terracotta, darker at the rim.
        const tone = 0.85 + 0.15 * Math.sin(tx * 12.9 + ty * 78.2);
        const rim = Math.min(1, edge / 0.12);
        const k = tone * (0.85 + 0.15 * rim) + 0.08 * fbm3(u * 3, v * 3, 7, 4);
        px.set([196 * k, 112 * k, 78 * k, 255].map((c) => Math.max(0, Math.min(255, c))), o);
      }
    }
  }
  return png(size, size, px);
}
writeFileSync(OUT + 'tiles.png', tiles());

// ---------------------------------------------------------------- studio.hdr
function studio(W = 256, H = 128) {
  const data = new Float32Array(W * H * 4);
  // Softboxes: direction (unit), angular half-size (radians), radiance (nits).
  const boxes = [
    { dir: norm([-0.6, 0.55, 0.55]), w: 0.32, h: 0.22, L: 9000 },
    { dir: norm([0.8, 0.35, 0.3]), w: 0.14, h: 0.3, L: 5000 },
    { dir: norm([0.1, 0.95, -0.2]), w: 0.4, h: 0.4, L: 2500 },
  ];
  for (let j = 0; j < H; j++) {
    for (let i = 0; i < W; i++) {
      const d = dirFromEquirect((i + 0.5) / W, (j + 0.5) / H);
      // Grey cyclorama: floor darker, walls fading up.
      let L = d[1] < 0 ? 60 : 90 + 120 * d[1];
      for (const b of boxes) {
        const x = norm(cross([0, 1, 0], b.dir)), y = cross(b.dir, x);
        const c = dot(d, b.dir);
        if (c <= 0) continue;
        const px = dot(d, x) / c, py = dot(d, y) / c;
        const e = Math.max(Math.abs(px) / b.w, Math.abs(py) / b.h);
        if (e < 1) L += b.L * (1 - 0.3 * e * e);
        else L += b.L * 0.02 * Math.exp(-(e - 1) * 6);
      }
      const o = (j * W + i) * 4;
      data.set([L, L * 0.98, L * 0.95, 1], o);
    }
  }
  return Buffer.from(encodeHDR({ width: W, height: H, data }));
}
const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const norm = (a) => { const l = Math.hypot(...a); return a.map((v) => v / l); };
writeFileSync(OUT + 'studio.hdr', studio());

console.log('wrote examples/assets/vase.obj, tiles.png, studio.hdr');
