/**
 * Heuristic intent catalog (DESIGN.md 3.1, 3.3, 7).
 *
 * Each class names the agents it summons (catalog ids from src/agents/catalog.ts), the capabilities it
 * reports as `required_tools` (schemas/intent.schema.json), the tool-name globs its plan steps may use,
 * the workspace resources it implies, and a plan template. Plans are DAGs; the Commander is never a
 * step because the orchestrator merges every plan through it.
 */
import type { MemoryCategory } from "../kernel/types";

export interface PlanTemplateStep {
  id: string;
  agent: string;
  /** Placeholders: {text} (the user's words), {topic}, {language}, {files}. */
  task: string;
  dependsOn: string[];
}

export interface IntentClass {
  intent: string;
  label: string;
  description: string;
  /** Keyword (or space-separated phrase) -> weight. Matched after the same light stemming as the input. */
  keywords: Record<string, number>;
  agents: string[];
  /** Capability names reported as `required_tools`, e.g. "git", "filesystem". */
  requiredTools: string[];
  /** Tool-name globs plan steps may use (intersected with each agent's own tools). */
  tools: string[];
  /** Workspace resources the generator should assemble, e.g. "Glossary", "Style Guide". */
  resources: string[];
  /** Memory the Context Loader recalls for this class. */
  memory: MemoryCategory[];
  /** Priority when the text has no priority cue. */
  defaultPriority?: "high";
  plan: PlanTemplateStep[];
}

export const FALLBACK_INTENT = "general_task";

const READ_TOOLS = ["fs.list_files", "fs.read_file", "fs.search_text", "search.*", "memory.recall"];

/** Capability name -> tool-name globs. Unknown capabilities are treated as MCP server names. */
export const CAPABILITY_TOOLS: Record<string, string[]> = {
  filesystem: ["fs.*"],
  git: ["git.*"],
  search: ["search.*", "fs.search_text"],
  memory: ["memory.*"],
  tests: ["proc.run_tests"],
  deploy: ["proc.deploy"],
};

export function capabilityGlobs(capability: string): string[] {
  const key = capability.trim().toLowerCase();
  return CAPABILITY_TOOLS[key] ?? [`mcp.${key}.*`];
}

export const INTENT_CATALOG: IntentClass[] = [
  {
    intent: "engineering_review",
    label: "Engineering review",
    description: "Review a module or change: architecture, code defects and test coverage.",
    keywords: {
      review: 3,
      "code review": 4,
      "pull request": 3,
      pr: 2,
      inspect: 2,
      examine: 2,
      assess: 2,
      evaluate: 1.5,
      analyze: 1.5,
      analyse: 1.5,
      quality: 1.5,
      architecture: 2,
      module: 1,
      code: 1,
      codebase: 1.5,
      dependency: 1,
      refactor: 1,
    },
    agents: ["systems_architect", "code_reviewer", "qa_engineer"],
    requiredTools: ["git", "filesystem"],
    tools: [...READ_TOOLS, "git.*"],
    resources: [],
    memory: ["coding_standard", "architecture_decision"],
    plan: [
      { id: "s1", agent: "systems_architect", task: "Map the module boundaries and dependencies relevant to: {text}", dependsOn: [] },
      { id: "s2", agent: "code_reviewer", task: "Review the code for defects, risky patterns and coding-standard violations: {text}", dependsOn: [] },
      { id: "s3", agent: "qa_engineer", task: "Check test coverage for the code under review, focusing on the areas the review flagged: {text}", dependsOn: ["s2"] },
    ],
  },
  {
    intent: "feature_build",
    label: "Feature build",
    description: "Plan, design, implement, test and document a new feature.",
    keywords: {
      build: 3,
      implement: 3,
      feature: 3,
      develop: 2.5,
      integrate: 2,
      refactor: 2,
      add: 1.5,
      create: 1.5,
      endpoint: 1.5,
      new: 1,
      component: 1,
      support: 1,
      make: 1,
    },
    agents: ["planner", "systems_architect", "fullstack_engineer", "qa_engineer", "documentation"],
    requiredTools: ["filesystem", "git", "tests"],
    tools: [...READ_TOOLS, "git.*", "fs.write_output", "fs.write_file", "proc.run_tests"],
    resources: [],
    memory: ["coding_standard", "architecture_decision"],
    plan: [
      { id: "s1", agent: "planner", task: "Split the feature into ordered, testable tasks: {text}", dependsOn: [] },
      { id: "s2", agent: "systems_architect", task: "Decide where the feature fits in the module structure and which files change: {text}", dependsOn: ["s1"] },
      { id: "s3", agent: "fullstack_engineer", task: "Implement the feature following the plan and the coding standards: {text}", dependsOn: ["s2"] },
      { id: "s4", agent: "qa_engineer", task: "Test the new feature and report failures and untested paths: {text}", dependsOn: ["s3"] },
      { id: "s5", agent: "documentation", task: "Document the new feature and every changed public symbol: {text}", dependsOn: ["s3"] },
    ],
  },
  {
    intent: "website_localization",
    label: "Website localization",
    description: "Adapt a website or app to another locale: voice, translation, localization QA and SEO.",
    keywords: {
      localize: 4,
      localise: 4,
      localization: 4,
      localisation: 4,
      i18n: 4,
      l10n: 4,
      locale: 3,
      multilingual: 3,
      website: 2,
      "landing page": 2,
      string: 1.5,
      site: 1.5,
      app: 1.5,
      translate: 1.5,
      seo: 1.5,
      page: 1,
    },
    agents: ["brand_analyst", "translator", "localization_qa", "seo_reviewer"],
    requiredTools: ["filesystem", "search"],
    tools: [...READ_TOOLS, "fs.write_output"],
    resources: ["Style Guide"],
    memory: ["translation_guide", "preference"],
    plan: [
      { id: "s1", agent: "brand_analyst", task: "Extract the brand voice, tone and do-not-translate terms for the style guide: {text}", dependsOn: [] },
      { id: "s2", agent: "translator", task: "Translate the site content into {language} following the style guide and glossary: {text}", dependsOn: ["s1"] },
      { id: "s3", agent: "localization_qa", task: "Check the {language} content for glossary violations, truncation risks and untranslated strings", dependsOn: ["s2"] },
      { id: "s4", agent: "seo_reviewer", task: "Check localized titles, meta descriptions and lang attributes for {language}", dependsOn: ["s2"] },
    ],
  },
  {
    intent: "legal_translation",
    label: "Legal translation",
    description: "Translate a contract or other legal document with a glossary of defined terms and a QA pass.",
    keywords: {
      contract: 4,
      legal: 4,
      nda: 4,
      agreement: 3,
      clause: 3,
      lease: 3,
      "terms of service": 3,
      law: 2,
      translate: 2,
      translation: 2,
      terms: 1.5,
    },
    agents: ["legal", "translator", "qa_reviewer"],
    requiredTools: ["filesystem"],
    tools: [...READ_TOOLS, "fs.write_output"],
    resources: ["Glossary", "Source File", "Output Folder"],
    memory: ["translation_guide"],
    plan: [
      { id: "s1", agent: "legal", task: "List the defined terms, obligations, dates and risky clauses, and build the glossary: {text}", dependsOn: [] },
      { id: "s2", agent: "translator", task: "Translate the document into {language}, using the glossary for every defined term: {text}", dependsOn: ["s1"] },
      { id: "s3", agent: "qa_reviewer", task: "Check the translation against the source: terms, numbering and cross-references", dependsOn: ["s2"] },
    ],
  },
  {
    intent: "document_translation",
    label: "Translation",
    description: "Translate a document or text that is neither legal nor a website.",
    keywords: { translate: 3, translation: 3, language: 1 },
    agents: ["translator", "qa_reviewer"],
    requiredTools: ["filesystem"],
    tools: [...READ_TOOLS, "fs.write_output"],
    resources: ["Glossary", "Output Folder"],
    memory: ["translation_guide"],
    plan: [
      { id: "s1", agent: "translator", task: "Translate into {language}, keeping formatting and placeholders intact: {text}", dependsOn: [] },
      { id: "s2", agent: "qa_reviewer", task: "Check the translation against the source", dependsOn: ["s1"] },
    ],
  },
  {
    intent: "bug_fix",
    label: "Bug fix",
    description: "Find the cause of a defect, fix it and verify the fix with tests.",
    keywords: {
      bug: 4,
      fix: 4,
      crash: 4,
      outage: 4,
      broken: 3,
      debug: 3,
      exception: 3,
      regression: 3,
      defect: 3,
      "not working": 3,
      incident: 3,
      error: 2,
      fail: 2,
      failing: 2,
      issue: 2,
      repair: 2,
      patch: 2,
      down: 2,
    },
    agents: ["code_reviewer", "fullstack_engineer", "qa_engineer"],
    requiredTools: ["filesystem", "git", "tests"],
    tools: [...READ_TOOLS, "git.*", "fs.write_output", "fs.write_file", "proc.run_tests"],
    resources: [],
    memory: ["coding_standard", "project_history"],
    defaultPriority: "high",
    plan: [
      { id: "s1", agent: "code_reviewer", task: "Locate the cause of the defect and name the file and line: {text}", dependsOn: [] },
      { id: "s2", agent: "fullstack_engineer", task: "Fix the defect with a minimal, reviewable change and a regression test: {text}", dependsOn: ["s1"] },
      { id: "s3", agent: "qa_engineer", task: "Run the tests and confirm the fix: {text}", dependsOn: ["s2"] },
    ],
  },
  {
    intent: "documentation",
    label: "Documentation",
    description: "Write or update documentation for code or a feature.",
    keywords: {
      documentation: 4,
      docs: 4,
      readme: 4,
      document: 3,
      tutorial: 3,
      changelog: 3,
      "release notes": 3,
      docstring: 3,
      jsdoc: 3,
      doc: 2,
      guide: 2,
      comment: 1.5,
    },
    agents: ["researcher", "documentation"],
    requiredTools: ["filesystem", "search"],
    tools: [...READ_TOOLS, "fs.write_output"],
    resources: ["Output Folder"],
    memory: ["coding_standard", "project_history"],
    plan: [
      { id: "s1", agent: "researcher", task: "Collect the files and facts the documentation must cover: {text}", dependsOn: [] },
      { id: "s2", agent: "documentation", task: "Write the documentation: {text}", dependsOn: ["s1"] },
    ],
  },
  {
    intent: "research",
    label: "Research",
    description: "Find out what the project already knows about a topic and where it lives.",
    keywords: {
      research: 4,
      investigate: 3,
      "look into": 3,
      "find out": 3,
      "how does": 3,
      understand: 2.5,
      explore: 2.5,
      find: 2,
      where: 2,
      search: 2,
      compare: 2,
      locate: 2,
      why: 1.5,
      learn: 1.5,
      how: 1,
      what: 1,
      question: 1,
    },
    agents: ["researcher"],
    requiredTools: ["filesystem", "search"],
    tools: [...READ_TOOLS],
    resources: [],
    memory: ["project_history", "architecture_decision"],
    plan: [{ id: "s1", agent: "researcher", task: "Find and summarize what the project knows about: {text}", dependsOn: [] }],
  },
  {
    intent: "test_run",
    label: "Test run",
    description: "Run the test suite and report failures and coverage gaps.",
    keywords: {
      test: 4,
      "unit test": 4,
      coverage: 3,
      vitest: 3,
      jest: 3,
      pytest: 3,
      qa: 3,
      spec: 2,
      ci: 1,
    },
    agents: ["qa_engineer"],
    requiredTools: ["filesystem", "tests"],
    tools: [...READ_TOOLS, "proc.run_tests"],
    resources: [],
    memory: ["coding_standard"],
    plan: [{ id: "s1", agent: "qa_engineer", task: "Run the test suite and report failures and untested paths: {text}", dependsOn: [] }],
  },
  {
    intent: "security_audit",
    label: "Security audit",
    description: "Scan for leaked secrets, vulnerabilities and unsafe patterns.",
    keywords: {
      security: 4,
      vulnerability: 4,
      vuln: 4,
      cve: 4,
      injection: 4,
      xss: 4,
      owasp: 4,
      pentest: 4,
      secure: 3,
      secret: 3,
      credential: 3,
      "api key": 3,
      password: 3,
      exploit: 3,
      leak: 3,
      audit: 3,
      permission: 2,
      auth: 1.5,
    },
    agents: ["security_agent", "code_reviewer"],
    requiredTools: ["filesystem", "git"],
    tools: [...READ_TOOLS, "git.*"],
    resources: [],
    memory: ["coding_standard"],
    defaultPriority: "high",
    plan: [
      { id: "s1", agent: "security_agent", task: "Scan for leaked credentials and unsafe code; report file and line, never secret values: {text}", dependsOn: [] },
      { id: "s2", agent: "code_reviewer", task: "Review input handling, auth checks and injection risks: {text}", dependsOn: [] },
    ],
  },
  {
    intent: "deployment",
    label: "Deployment",
    description: "Verify and ship a build through the configured deploy command.",
    keywords: {
      deploy: 4,
      deployment: 4,
      release: 3,
      ship: 3,
      publish: 3,
      rollout: 3,
      "roll out": 3,
      "go live": 3,
      pipeline: 2,
      production: 2,
      prod: 2,
      staging: 2,
      docker: 2,
      kubernetes: 2,
      ci: 1,
    },
    agents: ["qa_engineer", "devops_engineer"],
    requiredTools: ["filesystem", "git", "tests", "deploy"],
    tools: [...READ_TOOLS, "git.*", "proc.run_tests", "proc.deploy"],
    resources: [],
    memory: ["architecture_decision", "project_history"],
    plan: [
      { id: "s1", agent: "qa_engineer", task: "Run the test suite before deploying and report any failure: {text}", dependsOn: [] },
      { id: "s2", agent: "devops_engineer", task: "Deploy through the configured deploy command once tests pass: {text}", dependsOn: ["s1"] },
    ],
  },
  {
    intent: "design_review",
    label: "Design review",
    description: "Review screens for usability, accessibility and visual consistency.",
    keywords: {
      "user interface": 4,
      "user experience": 4,
      accessibility: 4,
      a11y: 4,
      usability: 4,
      design: 3,
      "design review": 3,
      ui: 3,
      ux: 3,
      layout: 3,
      mockup: 3,
      wireframe: 3,
      screen: 2,
      css: 2,
      visual: 2,
      color: 1.5,
      style: 1,
      review: 1,
    },
    agents: ["ux_agent", "designer"],
    requiredTools: ["filesystem"],
    tools: [...READ_TOOLS],
    resources: [],
    memory: ["preference"],
    plan: [
      { id: "s1", agent: "ux_agent", task: "Find usability and accessibility problems in the relevant screens: {text}", dependsOn: [] },
      { id: "s2", agent: "designer", task: "Review visual consistency and legibility: {text}", dependsOn: [] },
    ],
  },
  {
    intent: "summarize",
    label: "Summary",
    description: "Summarize files, documents or a topic.",
    keywords: {
      summarize: 4,
      summarise: 4,
      summary: 4,
      tldr: 4,
      "tl dr": 4,
      overview: 3,
      recap: 3,
      condense: 3,
      "sum up": 3,
      digest: 2,
      brief: 2,
      explain: 2,
    },
    agents: ["researcher", "writer"],
    requiredTools: ["filesystem", "search"],
    tools: [...READ_TOOLS, "fs.write_output"],
    resources: [],
    memory: ["project_history"],
    plan: [
      { id: "s1", agent: "researcher", task: "Collect the files and facts to summarize: {text}", dependsOn: [] },
      { id: "s2", agent: "writer", task: "Write a concise summary: {text}", dependsOn: ["s1"] },
    ],
  },
  {
    intent: FALLBACK_INTENT,
    label: "General task",
    description: "Anything else: collect context, then plan the work.",
    keywords: {},
    agents: ["researcher", "planner"],
    requiredTools: ["filesystem", "search"],
    tools: [...READ_TOOLS],
    resources: [],
    memory: ["project_history", "preference"],
    plan: [
      { id: "s1", agent: "researcher", task: "Collect the files and memory relevant to: {text}", dependsOn: [] },
      { id: "s2", agent: "planner", task: "Turn the request into an ordered task list with done conditions: {text}", dependsOn: ["s1"] },
    ],
  },
];

export function findIntentClass(intent: string): IntentClass | undefined {
  return INTENT_CATALOG.find((c) => c.intent === intent);
}

/** Language names (and country names after "for"/"to"/"in") -> ISO 639-1. */
export const LANGUAGES: Record<string, string> = {
  indonesian: "id",
  "bahasa indonesia": "id",
  bahasa: "id",
  english: "en",
  spanish: "es",
  french: "fr",
  german: "de",
  japanese: "ja",
  chinese: "zh",
  mandarin: "zh",
  korean: "ko",
  portuguese: "pt",
  italian: "it",
  dutch: "nl",
  russian: "ru",
  arabic: "ar",
  hindi: "hi",
  vietnamese: "vi",
  thai: "th",
  malay: "ms",
  turkish: "tr",
  polish: "pl",
  swedish: "sv",
  javanese: "jv",
  sundanese: "su",
  tagalog: "tl",
  filipino: "tl",
};

export const COUNTRY_LANGUAGES: Record<string, string> = {
  indonesia: "id",
  japan: "ja",
  germany: "de",
  france: "fr",
  spain: "es",
  mexico: "es",
  china: "zh",
  korea: "ko",
  brazil: "pt",
  portugal: "pt",
  italy: "it",
  netherlands: "nl",
  vietnam: "vi",
  thailand: "th",
  malaysia: "ms",
};

export const LANGUAGE_NAMES: Record<string, string> = {
  id: "Indonesian",
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  ja: "Japanese",
  zh: "Chinese",
  ko: "Korean",
  pt: "Portuguese",
  it: "Italian",
  nl: "Dutch",
  ru: "Russian",
  ar: "Arabic",
  hi: "Hindi",
  vi: "Vietnamese",
  th: "Thai",
  ms: "Malay",
  tr: "Turkish",
  pl: "Polish",
  sv: "Swedish",
  jv: "Javanese",
  su: "Sundanese",
  tl: "Tagalog",
};
